# -*- coding: utf-8 -*-
"""Taller Vigenère.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jIygQ7MIl0y50kki3SjIsGT8_Qdt9kla

# **Cifrado Taller Vigenère HOMEWORK**
## Anderson Stick Barrera Tovar
### 1000623506

Implementar el algoritmo de Vigenère en el lenguaje Python teniendo en cuenta lo siguiente:
El programa debe correr en modo línea de comando

Ciframiento
- Desde la consola debe recibir la clave, el parámetro t y el mensaje a cifrar
- Como resultado debe generar el texto cifrado

Decifrafiemto
- Desde la consola debe recibir la clave, el parámetro t y el texto cifrado
- Como resultado debe generar el mensaje en texto claro

Cargar en esta tarea un archivo ZIP con lo siguiente:
- Archivo Python
- Pequeño video o screenshot (pantallazo) en donde se muestre funcionar el algoritmo

THERE IS A SECRET PASSAGE BEHIND THE PICTURE FRAME
THEREISASECRETPASSAGEBEHINDTHEPICTUREFRAME

KEYWORD= CRYPTO

t=3

El separar por t es para entender la teoría y ver de cada cuantos carácteres se debe separar el mensaje, sin embargo no tiene mucho efecto en el crifrado
"""

def three_characters_separate(mensaje):
    grupos_de_tres = [mensaje[i:i+3] for i in range(0, len(mensaje), 3)]
    return ' '.join(grupos_de_tres)

# Example usage
mensaje = "THEREISASECRETPASSAGEBEHINDTHEPICTUREFRAME"
mensaje_separado = three_characters_separate(mensaje)
print("Mensaje separado por grupos de tres caracteres:")
print(mensaje_separado)

"""CRY PTO CRY PTO CRY PTO CRY PTO CRY PTO CRY PTO CRY PTO

THE REI SAS ECR ETP ASS AGE BEH IND THE PIC TUR EFR AME

VYC GXW URQ TVF GKN PLG CXC QXV KEB IAS RZA INF GWP PFS

Primero se quitan los espacios entre palabras
"""

def remove_spaces(sentence):
    return ''.join(sentence.split())

sentence = "THERE IS A SECRET PASSAGE BEHIND THE PICTURE FRAME"
sentence_without_spaces = remove_spaces(sentence)
print("Sentence without spaces:", sentence_without_spaces)

def vigenere_cipher(message, keyword, t):
    alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    result = ''
    repeated_keyword = (keyword * (len(message) // len(keyword))) + keyword[:len(message) % len(keyword)]

    for i in range(len(message)):
        if message[i].isalpha():
            shift = alphabet.index(repeated_keyword[i].upper())
            if message[i].islower():
                result += chr((ord(message[i]) - ord('a') + shift) % 26 + ord('a'))
            else:
                result += chr((ord(message[i]) - ord('A') + shift) % 26 + ord('A'))
        else:
            result += message[i]

    if t > 0:
        result = ' '.join([result[i:i+t] for i in range(0, len(result), t)])

    return result

# Example usage
message = sentence_without_spaces
keyword = "CRYPTO"
t = 3

encrypted_message = vigenere_cipher(message, keyword, t)
print("Message to encrypt: ", message)
print("Keyword: ", keyword)
print("Encrypted message:", encrypted_message)

# Console example usage
keyword = input("Enter the keyword: ")
t = int(input("t = "))
message = remove_spaces(input("Enter the message to encrypt: "))

encrypted_message = vigenere_cipher(message, keyword, t)
print("Message to encrypt: ", message)
print("Keyword: ", keyword)
print("Encrypted message:", encrypted_message)

"""# Descifrado"""

def vigenere_decipher(encrypted_message, keyword, t):
    alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    result = ''
    repeated_keyword = (keyword * (len(encrypted_message) // len(keyword))) + keyword[:len(encrypted_message) % len(keyword)]

    for i in range(len(encrypted_message)):
        if encrypted_message[i].isalpha():
            shift = alphabet.index(repeated_keyword[i].upper())
            if encrypted_message[i].islower():
                result += chr((ord(encrypted_message[i]) - ord('a') - shift) % 26 + ord('a'))
            else:
                result += chr((ord(encrypted_message[i]) - ord('A') - shift) % 26 + ord('A'))
        else:
            result += encrypted_message[i]

    if t > 0:
        result = ' '.join([result[i:i+t] for i in range(0, len(result), t)])

    return result

# Example usage
encrypted_message = remove_spaces("VYC GXW URQ TVF GKN PLG CXC QXV KEB IAS RZA INF GWP PFS")
keyword = "CRYPTO"
decrypted_message = vigenere_decipher(encrypted_message, keyword, t)
print("Decrypted message:", decrypted_message)

# Console example usage
keyword = input("Enter the keyword: ")
t = int(input("t = "))
encrypted_message = remove_spaces(input("Enter the encrypted message: "))

# encrypted_message = remove_spaces("VYC GXW URQ TVF GKN PLG CXC QXV KEB IAS RZA INF GWP PFS")
decrypted_message = vigenere_decipher(encrypted_message, keyword, t)
print("Decrypted message:", decrypted_message)